_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 256
buffer_size:
    value: 1000000
eval_freq:
    value: 10
explore_noise:
    value: 0.1
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
noise_clip:
    value: 0.5
policy_delay:
    value: 2
policy_noise:
    value: 0.2
save_freq:
    value: 100
tau:
    value: 0.005
