_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.7
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 256
capacity:
    value: 100000
draw_reward:
    value: 0
exploration_noise:
    value: 0.1
exploration_noise_decay_rate:
    value: 0.9997
exploration_noise_method:
    value: decay
gamma:
    value: 0.99
hard_update_decay_rate:
    value: 0.95
hard_update_frequency:
    value: 2000
initial_exploration_noise:
    value: 0.4
initial_policy_noise:
    value: 0.4
lose_reward:
    value: -10
lower_bound:
    value: 1000
lr:
    value: 0.0003
model_dim:
    value: 256
noise_clip:
    value: 0.5
only_self_play:
    value: false
policy_delay:
    value: 2
policy_noise:
    value: 0.2
policy_noise_decay_rate:
    value: 0.9997
policy_noise_method:
    value: decay
puck_closeness_reward_multiplier:
    value: 1
puck_direction_reward_multiplier:
    value: 1
puck_not_touched_yet_reward:
    value: 0
puck_touch_reward_multiplier:
    value: 1
render:
    value: false
save_every:
    value: 100
save_folder:
    value: checkpoints/2025-02-22_14-17-57
tau:
    value: 0.005
training_episodes:
    value: 100
update_type:
    value: hard
win_reward:
    value: 10
